apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f chinook-compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f chinook-compose.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: chinook_db
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/postgres-password
            - name: POSTGRES_USER
              value: myuser
          image: postgres:17
          name: chinook-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: postgres-password
              subPath: postgres-password
            - mountPath: /docker-entrypoint-initdb.d/Chinook_PostgreSql.sql
              name: db-cm0
              subPath: Chinook_PostgreSql.sql
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-password
          secret:
            items:
              - key: postgres-password
                path: postgres-password
            secretName: postgres-password
        - configMap:
            items:
              - key: Chinook_PostgreSql.sql
                path: Chinook_PostgreSql.sql
            name: db-cm0
          name: db-cm0
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
