apiVersion: v1
kind: PersistentVolume
metadata:
  name: chinook-api-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  local:
    path: /chinook-api-app
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - chinook-api-worker