apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chinook-api-pvc
  namespace: fastapi-chinook
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi