apiVersion: v1
kind: Service
metadata:
  name: chinook-api
  namespace: fastapi-chinook
spec:
  selector:
    app: chinook-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: chinook-db
  namespace: fastapi-chinook
spec:
  selector:
    app: chinook-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP